-- Fashionphile schema setup
USE DATABASE RETAIL_ANALYZER;

CREATE SCHEMA IF NOT EXISTS FASHIONPHILE;
USE SCHEMA FASHIONPHILE;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);

CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    DESIGNER        VARCHAR(500),
    CONDITION       VARCHAR(100),
    CATEGORY        VARCHAR(200),
    COLOR           VARCHAR(100),
    MATERIAL        VARCHAR(200),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);

CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Fashionphile';

CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    IGNORE_UTF8_ERRORS = TRUE;

CREATE STAGE IF NOT EXISTS SCRAPE_DATA
    FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';

CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID,
    p.RUN_ID,
    sq.QUERY_ID,
    sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT,
    p.TITLE,
    p.PRICE,
    p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE,
    p.ORIGINAL_PRICE_NUMERIC,
    p.DISCOUNT,
    CASE
        WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
        THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1)
    END AS DISCOUNT_PCT,
    p.LINK,
    p.IMAGE_PATH,
    p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.DESIGNER,
    p.CONDITION,
    p.CATEGORY,
    p.COLOR,
    p.MATERIAL,
    p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;
