-- ============================================================
-- Retail Analyzer — Full Snowflake + SPCS Setup
-- Run once on a new Snowflake account with ACCOUNTADMIN role.
--
-- Creates:
--   1. Database + all 7 marketplace schemas (tables, stages, views)
--   2. SPCS image repository + compute pool
--   3. Network egress rules for scraping
--   4. External access integration
--   5. Network policy for SPCS ingress
--   6. Snowflake secret for key-pair auth inside containers
--
-- NOTE: Replace placeholder values marked with <ANGLE_BRACKETS>.
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS RETAIL_ANALYZER;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

USE DATABASE RETAIL_ANALYZER;
USE WAREHOUSE COMPUTE_WH;

-- ════════════════════════════════════════════════════════════
-- SECTION 1: MARKETPLACE SCHEMAS
-- ════════════════════════════════════════════════════════════

-- ── Google Shopping ─────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS GOOGLE_SHOPPING;
USE SCHEMA GOOGLE_SHOPPING;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    SELLER          VARCHAR(500),
    RATING          VARCHAR(20),
    RATING_NUMERIC  NUMBER(3,1),
    REVIEWS         VARCHAR(50),
    LINK            VARCHAR(4000),
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    SHIPPING        VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Google Shopping';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.SELLER, p.RATING, p.RATING_NUMERIC, p.REVIEWS,
    CASE
        WHEN p.REVIEWS LIKE '%K' THEN TRY_CAST(REPLACE(p.REVIEWS, 'K', '') AS NUMBER) * 1000
        WHEN p.REVIEWS LIKE '%M' THEN TRY_CAST(REPLACE(p.REVIEWS, 'M', '') AS NUMBER) * 1000000
        ELSE TRY_CAST(p.REVIEWS AS NUMBER)
    END AS REVIEWS_NUMERIC,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.SHIPPING, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;

-- ── Grailed ─────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS GRAILED;
USE SCHEMA GRAILED;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    DESIGNER        VARCHAR(500),
    CONDITION       VARCHAR(100),
    SIZE_INFO       VARCHAR(100),
    SELLER_LOCATION VARCHAR(200),
    DEPARTMENT      VARCHAR(50),
    CATEGORY        VARCHAR(200),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Grailed';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.DESIGNER, p.CONDITION, p.SIZE_INFO, p.SELLER_LOCATION,
    p.DEPARTMENT, p.CATEGORY, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;

-- ── Vestiaire Collective ────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS VESTIAIRE;
USE SCHEMA VESTIAIRE;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    DESIGNER        VARCHAR(500),
    CONDITION       VARCHAR(100),
    SIZE_INFO       VARCHAR(100),
    MATERIAL        VARCHAR(200),
    CATEGORY        VARCHAR(200),
    COLOR           VARCHAR(100),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Vestiaire Collective';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.DESIGNER, p.CONDITION, p.SIZE_INFO, p.MATERIAL, p.CATEGORY, p.COLOR, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;

-- ── Rebag ───────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS REBAG;
USE SCHEMA REBAG;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    DESIGNER        VARCHAR(500),
    CONDITION       VARCHAR(100),
    CATEGORY        VARCHAR(200),
    COLOR           VARCHAR(100),
    MATERIAL        VARCHAR(200),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Rebag';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.DESIGNER, p.CONDITION, p.CATEGORY, p.COLOR, p.MATERIAL, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;

-- ── Farfetch ────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS FARFETCH;
USE SCHEMA FARFETCH;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    DESIGNER        VARCHAR(500),
    PRE_OWNED       BOOLEAN        DEFAULT FALSE,
    CATEGORY        VARCHAR(200),
    COLOR           VARCHAR(100),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Farfetch';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.DESIGNER, p.PRE_OWNED, p.CATEGORY, p.COLOR, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;

-- ── Fashionphile ────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS FASHIONPHILE;
USE SCHEMA FASHIONPHILE;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    DESIGNER        VARCHAR(500),
    CONDITION       VARCHAR(100),
    CATEGORY        VARCHAR(200),
    COLOR           VARCHAR(100),
    MATERIAL        VARCHAR(200),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from Fashionphile';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.DESIGNER, p.CONDITION, p.CATEGORY, p.COLOR, p.MATERIAL, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;

-- ── 2nd Street USA ──────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS SECOND_STREET;
USE SCHEMA SECOND_STREET;

CREATE TABLE IF NOT EXISTS SEARCH_QUERIES (
    QUERY_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT        VARCHAR(500)   NOT NULL,
    FIRST_SEARCHED_AT TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT         TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_QUERY_TEXT UNIQUE (QUERY_TEXT)
);
CREATE TABLE IF NOT EXISTS SCRAPE_RUNS (
    RUN_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_ID        NUMBER         NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    COUNTRY         VARCHAR(10)    DEFAULT 'us',
    LANGUAGE        VARCHAR(10)    DEFAULT 'en',
    SCRAPED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    PRODUCT_COUNT   NUMBER,
    SOURCE_FILE     VARCHAR(500),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL REFERENCES SCRAPE_RUNS(RUN_ID),
    TITLE           VARCHAR(1000)  NOT NULL,
    PRICE           VARCHAR(50),
    PRICE_NUMERIC   NUMBER(10,2),
    ORIGINAL_PRICE  VARCHAR(50),
    ORIGINAL_PRICE_NUMERIC NUMBER(10,2),
    DISCOUNT        VARCHAR(50),
    LINK            VARCHAR(4000)  NOT NULL,
    IMAGE_PATH      VARCHAR(500),
    IMAGE_STAGE_PATH VARCHAR(500),
    BRAND           VARCHAR(500),
    CONDITION       VARCHAR(100),
    CATEGORY        VARCHAR(200),
    COLOR           VARCHAR(100),
    SIZE_INFO       VARCHAR(100),
    LOADED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS PRODUCT_QUERIES (
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    QUERY_ID      NUMBER NOT NULL REFERENCES SEARCH_QUERIES(QUERY_ID),
    FOUND_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_ID, QUERY_ID)
);
CREATE STAGE IF NOT EXISTS PRODUCT_IMAGES DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stores product thumbnail images scraped from 2nd Street USA';
CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
    TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE IGNORE_UTF8_ERRORS = TRUE;
CREATE STAGE IF NOT EXISTS SCRAPE_DATA FILE_FORMAT = JSON_FORMAT
    COMMENT = 'Landing stage for scraper JSON output files';
CREATE OR REPLACE VIEW PRODUCTS_ANALYSIS AS
SELECT
    p.PRODUCT_ID, p.RUN_ID, sq.QUERY_ID, sq.QUERY_TEXT AS SEARCH_QUERY,
    r.SCRAPED_AT, p.TITLE, p.PRICE, p.PRICE_NUMERIC,
    p.ORIGINAL_PRICE, p.ORIGINAL_PRICE_NUMERIC, p.DISCOUNT,
    CASE WHEN p.ORIGINAL_PRICE_NUMERIC > 0 AND p.PRICE_NUMERIC > 0
         THEN ROUND((1 - p.PRICE_NUMERIC / p.ORIGINAL_PRICE_NUMERIC) * 100, 1) END AS DISCOUNT_PCT,
    p.LINK, p.IMAGE_PATH, p.IMAGE_STAGE_PATH,
    BUILD_SCOPED_FILE_URL(@PRODUCT_IMAGES, p.IMAGE_STAGE_PATH) AS IMAGE_URL,
    p.BRAND, p.CONDITION, p.CATEGORY, p.COLOR, p.SIZE_INFO, p.LOADED_AT
FROM PRODUCTS p
JOIN SCRAPE_RUNS r ON p.RUN_ID = r.RUN_ID
JOIN SEARCH_QUERIES sq ON r.QUERY_ID = sq.QUERY_ID;


-- ════════════════════════════════════════════════════════════
-- SECTION 2: SPCS INFRASTRUCTURE
-- ════════════════════════════════════════════════════════════

USE SCHEMA PUBLIC;

-- ── Image Repository ────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS IMAGES;
CREATE IMAGE REPOSITORY IF NOT EXISTS RETAIL_ANALYZER.IMAGES.REPO;

-- ── Internal stage for the service spec YAML ────────────────
CREATE STAGE IF NOT EXISTS RETAIL_ANALYZER.PUBLIC.SPCS_SPECS
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- ── Compute Pool ────────────────────────────────────────────
-- CPU_X64_M = 6 vCPUs, 24 GB RAM.
-- The service spec sets per-container resource limits to fit.
CREATE COMPUTE POOL IF NOT EXISTS SCRAPER_POOL
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = CPU_X64_M
    AUTO_RESUME  = TRUE
    AUTO_SUSPEND_SECS = 3600;

-- ── Network Rule (egress to marketplace sites, CDNs, APIs, and Snowflake storage) ──
-- NOTE: The S3 hostname below is account-specific. If PUT operations fail inside
-- containers, check worker logs for the actual hostname and update this rule.
CREATE OR REPLACE NETWORK RULE RETAIL_ANALYZER.PUBLIC.SCRAPER_EGRESS_RULE
    TYPE = HOST_PORT
    MODE = EGRESS
    VALUE_LIST = (
        -- Snowflake internal stage storage (account-specific S3 bucket)
        'sfc-prod3-ds1-176-customer-stage.s3.amazonaws.com:443',
        -- Snowflake account endpoints
        'kyvowcp-gxb23745.snowflakecomputing.com:443',
        'bcb91379.snowflakecomputing.com:443',
        -- Marketplace sites
        'www.google.com:443',
        'shopping.google.com:443',
        'www.grailed.com:443',
        'us.vestiairecollective.com:443',
        'shop.rebag.com:443',
        'www.rebag.com:443',
        'www.farfetch.com:443',
        'www.fashionphile.com:443',
        '2ndstreetusa.com:443',
        'www.2ndstreetusa.com:443',
        'ec.2ndstreetusa.com:443',
        -- CDN / image hosts
        'cdn.shopify.com:443',
        'cdn-images.farfetch-contents.com:443',
        'images.vestiairecollective.com:443',
        'images.grailed.com:443',
        'media.grailed.com:443',
        -- Rebag GroupBy API
        'proxy.rebag.groupbycloud.com:443',
        -- Grailed Algolia search API
        'mnrwefss2q-dsn.algolia.net:443',
        'mnrwefss2q.algolia.net:443',
        'mnrwefss2q-1.algolianet.com:443',
        'mnrwefss2q-2.algolianet.com:443',
        'mnrwefss2q-3.algolianet.com:443',
        -- Playwright browser downloads (needed on first container start)
        'cdn.playwright.dev:443',
        'playwright.azureedge.net:443',
        -- Analytics / misc (loaded by marketplace pages)
        'www.googletagmanager.com:443',
        'www.google-analytics.com:443'
    );

-- ── External Access Integration ─────────────────────────────
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SCRAPER_EGRESS
    ALLOWED_NETWORK_RULES = (RETAIL_ANALYZER.PUBLIC.SCRAPER_EGRESS_RULE)
    ENABLED = TRUE;

-- ── Network Policy (required for SPCS public endpoint ingress) ──
-- 0.0.0.0/0 allows all IPs to reach the service endpoints.
-- For production, restrict to specific CIDRs.
CREATE NETWORK POLICY IF NOT EXISTS SPCS_INGRESS_POLICY
    ALLOWED_IP_LIST = ('0.0.0.0/0');

ALTER ACCOUNT SET NETWORK_POLICY = SPCS_INGRESS_POLICY;

-- ── Snowflake Secret (private key for auth inside containers) ──
-- Generate with:  base64 -i ~/.ssh/snowflake_rsa_key.p8 | tr -d '\n'
-- Then paste the output below replacing the placeholder.
USE SCHEMA RETAIL_ANALYZER.PUBLIC;
CREATE OR REPLACE SECRET RETAIL_ANALYZER.PUBLIC.SNOWFLAKE_KEY
    TYPE = GENERIC_STRING
    SECRET_STRING = '<PASTE_YOUR_BASE64_PRIVATE_KEY_HERE>';


-- ════════════════════════════════════════════════════════════
-- SECTION 3: VERIFICATION
-- ════════════════════════════════════════════════════════════

-- Copy the repository_url from this output — needed for deploy.sh
SHOW IMAGE REPOSITORIES IN SCHEMA RETAIL_ANALYZER.IMAGES;

SHOW COMPUTE POOLS LIKE 'SCRAPER_POOL';
SHOW NETWORK RULES IN SCHEMA RETAIL_ANALYZER.PUBLIC;
SHOW SECRETS IN SCHEMA RETAIL_ANALYZER.PUBLIC;
