-- Migration 001: Add LOADED_AT column to SEARCH_QUERIES, SCRAPE_RUNS,
-- and PRODUCT_QUERIES tables across all marketplace schemas.
-- The PRODUCTS table already has LOADED_AT -- these three were missing it.

ALTER TABLE SEARCH_QUERIES ADD COLUMN LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE SCRAPE_RUNS ADD COLUMN LOADED_AT TIMESTAMP_NTZ;
ALTER TABLE PRODUCT_QUERIES ADD COLUMN LOADED_AT TIMESTAMP_NTZ;
